services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ../data:/data
      - /volume1/music/dj-library-mirror:/library:ro
    env_file:
      - ../.env
    restart: unless-stopped
